
import os
import json
import re

DOCS_DIR = os.path.abspath("docs")
OUTPUT_JS = os.path.abspath("docs/report/js/docs_content.js")

def parse_markdown(text):
    """
    Very basic markdown cleanup for JSON embedding.
    The frontend will use 'marked.js' to render this, 
    so we just need to ensure it's safe string content.
    """
    return text

def scan_docs():
    structure = {}
    
    # Define the order we want
    categories = [
        "00_management",
        "01_specs",
        "02_research", 
        "03_stage1_reports"
    ]
    
    for cat in categories:
        cat_path = os.path.join(DOCS_DIR, cat)
        if not os.path.exists(cat_path):
            continue
            
        structure[cat] = []
        
        # List md files
        files = sorted([f for f in os.listdir(cat_path) if f.endswith(".md")])
        
        for f in files:
            full_path = os.path.join(cat_path, f)
            with open(full_path, "r", encoding="utf-8") as fr:
                content = fr.read()
                
            # Extract Title from first line if possible
            title = f
            lines = content.split('\n')
            for line in lines:
                if line.startswith("# "):
                    title = line.replace("# ", "").strip()
                    break
            
            structure[cat].append({
                "filename": f,
                "title": title,
                "content": content
            })
            
    return structure

def main():
    print(f"Scanning docs from: {DOCS_DIR}")
    data = scan_docs()
    
    # Read the README as global index
    readme_path = os.path.join(DOCS_DIR, "README_HE.md")
    readme_content = ""
    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            readme_content = f.read()

    # Scan Stages Breakdown
    stages_dir = os.path.join(DOCS_DIR, "stages_breakdown")
    stages_data = []
    if os.path.exists(stages_dir):
        print(f"Scanning stages from: {stages_dir}")
        files = sorted([f for f in os.listdir(stages_dir) if f.endswith(".md")])
        for f in files:
            full_path = os.path.join(stages_dir, f)
            with open(full_path, "r", encoding="utf-8") as fr:
                content = fr.read()
            
            title = f
            lines = content.split('\n')
            for line in lines:
                if line.startswith("# "):
                    title = line.replace("# ", "").strip()
                    break
            
            stages_data.append({
                "filename": f,
                "title": title,
                "content": content
            })

    js_content = f"""
// Auto-generated by scripts/generate_report_data.py
const DOCS_INDEX = {json.dumps(readme_content, ensure_ascii=False)};

const DOCS_STRUCTURE = {json.dumps(data, ensure_ascii=False)};

const STAGES_STRUCTURE = {json.dumps(stages_data, ensure_ascii=False)};
"""

    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"Generated {OUTPUT_JS}")

if __name__ == "__main__":
    main()
