"""
Adapters for model components.
These wrap existing model implementations to conform to Protocol interfaces.
"""

from typing import List, Optional
from dataclasses import dataclass
import numpy as np

from src.interfaces.protocols import (
    IFeatureExtractor,
    IEmbeddingResult,
    IClassifier,
    IFeatureFusion,
    IFeatureVector,
    IBaselineResult,
    IVariabilityResult,
    IDeceleration,
    ITachysystoleResult,
    ISinusoidalResult,
)

from src.models.moment_encoder import MomentFeatureExtractor, EmbeddingResult
from src.models.classifier import XGBClassifierWrapper
from src.models.fusion import build_feature_vector, FeatureVector


@dataclass
class AdapterEmbeddingResult:
    """
    Wrapper for embedding results from MomentFeatureExtractor.
    
    The MomentFeatureExtractor.extract() returns a raw numpy array,
    so this adapter wraps it to conform to IEmbeddingResult protocol.
    """
    _embedding: np.ndarray
    _is_mock: bool = False
    
    @property
    def embedding(self) -> np.ndarray:
        """1024-dimensional embedding vector."""
        return self._embedding
    
    @property
    def is_mock(self) -> bool:
        """True if this was generated by mock mode."""
        return self._is_mock


class MomentAdapter(IFeatureExtractor):
    """
    Adapter for MOMENT feature extractor.
    
    Wraps MomentFeatureExtractor to conform to IFeatureExtractor interface.
    
    Args:
        use_mock: Use mock MOMENT (for testing without GPU).
        device: Device to use ('cpu', 'cuda', 'mps').
        
    Example:
        >>> adapter = MomentAdapter(use_mock=False, device='cuda')
        >>> result = adapter.extract(fhr_signal)
        >>> print(f"Embedding shape: {result.embedding.shape}")
    """
    
    def __init__(self, use_mock: bool = False, device: str = 'cpu'):
        self._extractor = MomentFeatureExtractor(use_mock=use_mock, device=device)
        self._use_mock = use_mock or self._extractor.use_mock
    
    def extract(self, signal: np.ndarray) -> IEmbeddingResult:
        """Extract embeddings using MOMENT."""
        # MomentFeatureExtractor.extract() returns np.ndarray directly
        embedding_array = self._extractor.extract(signal)
        return AdapterEmbeddingResult(
            _embedding=embedding_array,
            _is_mock=self._use_mock
        )


class ClassifierAdapter(IClassifier):
    """
    Adapter for XGBoost classifier.
    
    Wraps XGBClassifierWrapper to conform to IClassifier interface.
    
    Args:
        model_path: Optional path to pre-trained model file.
        
    Example:
        >>> adapter = ClassifierAdapter(model_path="models/xgb_demo.json")
        >>> predictions = adapter.predict(X)
        >>> probas = adapter.predict_proba(X)
    """
    
    def __init__(self, model_path: Optional[str] = None):
        self._classifier = XGBClassifierWrapper()
        if model_path:
            self._classifier.load_model(model_path)
    
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict categories."""
        return self._classifier.predict(X)
    
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict probabilities."""
        return self._classifier.predict_proba(X)
    
    def save_model(self, path: str) -> None:
        """Save model to file."""
        self._classifier.save_model(path)
    
    def load_model(self, path: str) -> None:
        """Load model from file."""
        self._classifier.load_model(path)
    
    def train(self, X: np.ndarray, y: np.ndarray):
        """Train the classifier (passthrough to underlying model)."""
        return self._classifier.train(X, y)
    
    @property
    def is_trained(self) -> bool:
        """Check if classifier is trained."""
        return self._classifier.is_trained


class FusionAdapter(IFeatureFusion):
    """
    Adapter for feature fusion.
    
    Wraps build_feature_vector to conform to IFeatureFusion interface.
    
    Example:
        >>> adapter = FusionAdapter()
        >>> feature_vec = adapter.fuse(
        ...     embedding=embedding,
        ...     baseline=baseline_result,
        ...     variability=var_result,
        ...     decelerations=decels,
        ...     tachysystole=tachy_result,
        ...     sinusoidal=sinus_result
        ... )
        >>> print(f"Feature vector shape: {feature_vec.vector.shape}")
    """
    
    def fuse(
        self,
        embedding: np.ndarray,
        baseline: IBaselineResult,
        variability: IVariabilityResult,
        decelerations: List[IDeceleration],
        tachysystole: ITachysystoleResult,
        sinusoidal: ISinusoidalResult
    ) -> IFeatureVector:
        """Fuse features using existing implementation."""
        return build_feature_vector(
            embedding=embedding,
            baseline=baseline,
            variability=variability,
            decelerations=decelerations,
            tachysystole=tachysystole,
            sinusoidal=sinusoidal,
            start_idx=0,
            end_idx=0,
            start_time_sec=0,
            end_time_sec=0
        )
