"""
Adapters for model components.
These wrap existing model implementations to conform to Protocol interfaces.

Supports both MOMENT (legacy) and MiniRocket (recommended) encoders.
MiniRocket is 10-20x faster and uses 84 kernels vs 341M params.
"""

from typing import List, Optional, Union
from dataclasses import dataclass
import numpy as np
import logging

from src.interfaces.protocols import (
    IFeatureExtractor,
    IEmbeddingResult,
    IClassifier,
    IFeatureFusion,
    IFeatureVector,
    IBaselineResult,
    IVariabilityResult,
    IDeceleration,
    ITachysystoleResult,
    ISinusoidalResult,
)

# Try to import MiniRocket (preferred) or fallback to MOMENT
MINIROCKET_AVAILABLE = False
MOMENT_AVAILABLE = False

try:
    from src.models.minirocket_encoder import (
        MiniRocketEncoder, 
        MiniRocketConfig,
        generate_synthetic_training_data,
        SKTIME_AVAILABLE
    )
    MINIROCKET_AVAILABLE = SKTIME_AVAILABLE
except ImportError:
    pass

try:
    from src.models.moment_encoder import MomentFeatureExtractor, EmbeddingResult
    MOMENT_AVAILABLE = True
except ImportError:
    pass

from src.models.classifier import XGBClassifierWrapper
from src.models.fusion import build_feature_vector, FeatureVector

logger = logging.getLogger(__name__)


@dataclass
class AdapterEmbeddingResult:
    """
    Wrapper for embedding results from MomentFeatureExtractor.
    
    The MomentFeatureExtractor.extract() returns a raw numpy array,
    so this adapter wraps it to conform to IEmbeddingResult protocol.
    """
    _embedding: np.ndarray
    _is_mock: bool = False
    
    @property
    def embedding(self) -> np.ndarray:
        """1024-dimensional embedding vector."""
        return self._embedding
    
    @property
    def is_mock(self) -> bool:
        """True if this was generated by mock mode."""
        return self._is_mock


class MomentAdapter(IFeatureExtractor):
    """
    Adapter for MOMENT feature extractor (LEGACY - use MiniRocketAdapter instead).
    
    Wraps MomentFeatureExtractor to conform to IFeatureExtractor interface.
    
    NOTE: MOMENT requires PyTorch and momentfm packages. For faster inference,
    use MiniRocketAdapter instead (10-20x speedup).
    
    Args:
        use_mock: Use mock MOMENT (for testing without GPU).
        device: Device to use ('cpu', 'cuda', 'mps').
        
    Example:
        >>> adapter = MomentAdapter(use_mock=False, device='cuda')
        >>> result = adapter.extract(fhr_signal)
        >>> print(f"Embedding shape: {result.embedding.shape}")
    """
    
    def __init__(self, use_mock: bool = False, device: str = 'cpu'):
        if not MOMENT_AVAILABLE:
            raise ImportError(
                "MOMENT not available. Install with: pip install momentfm torch\n"
                "Or use MiniRocketAdapter instead (recommended)."
            )
        # Production version: no mock mode support
        if use_mock:
            raise ValueError(
                "MOMENT production version does not support mock mode. "
                "Use MiniRocketAdapter for testing instead."
            )
        self._extractor = MomentFeatureExtractor(device=device)
        self._use_mock = False
    
    def extract(self, signal: np.ndarray) -> IEmbeddingResult:
        """Extract embeddings using MOMENT."""
        # MomentFeatureExtractor.extract() returns np.ndarray directly
        embedding_array = self._extractor.extract(signal)
        return AdapterEmbeddingResult(
            _embedding=embedding_array,
            _is_mock=self._use_mock
        )


class MiniRocketAdapter(IFeatureExtractor):
    """
    Adapter for MiniRocket feature extractor (RECOMMENDED).
    
    MiniRocket is 10-20x faster than MOMENT and uses only 84 kernels
    vs 341M parameters. Achieves comparable accuracy on CTG classification.
    
    Args:
        model_path: Path to pre-fitted MiniRocket model. If None or not found,
                   will attempt cold start with synthetic data.
        auto_fit: If True, automatically fit on synthetic data if no model found.
        
    Example:
        >>> adapter = MiniRocketAdapter()
        >>> result = adapter.extract(fhr_signal)
        >>> print(f"Feature shape: {result.embedding.shape}")
    """
    
    def __init__(
        self, 
        model_path: Optional[str] = "models/minirocket_encoder.joblib",
        auto_fit: bool = True
    ):
        if not MINIROCKET_AVAILABLE:
            raise ImportError(
                "MiniRocket not available. Install with: pip install sktime"
            )
        
        config = MiniRocketConfig(model_path=model_path)
        self._encoder = MiniRocketEncoder(config)
        
        # Cold start: fit on synthetic data if no pre-trained model
        if not self._encoder.is_fitted and auto_fit:
            logger.info("MiniRocket not fitted. Performing cold start with synthetic data...")
            X_synth, _ = generate_synthetic_training_data(n_samples=100)
            self._encoder.fit(X_synth)
            logger.info("Cold start complete. MiniRocket is ready.")
    
    def extract(self, signal: np.ndarray) -> IEmbeddingResult:
        """Extract features using MiniRocket."""
        result = self._encoder.extract_features(signal)
        return AdapterEmbeddingResult(
            _embedding=result.features,
            _is_mock=False
        )


def get_feature_extractor(
    backend: str = "auto",
    **kwargs
) -> IFeatureExtractor:
    """
    Factory function to get the best available feature extractor.
    
    Args:
        backend: One of 'auto', 'minirocket', 'moment'.
                'auto' prefers MiniRocket if available.
        **kwargs: Additional arguments passed to the adapter.
        
    Returns:
        IFeatureExtractor instance.
        
    Example:
        >>> extractor = get_feature_extractor()  # Auto-selects best
        >>> extractor = get_feature_extractor('minirocket')  # Force MiniRocket
    """
    if backend == "auto":
        if MINIROCKET_AVAILABLE:
            logger.info("Using MiniRocket feature extractor (recommended)")
            return MiniRocketAdapter(**kwargs)
        elif MOMENT_AVAILABLE:
            logger.warning("MiniRocket not available. Falling back to MOMENT (slower)")
            return MomentAdapter(**kwargs)
        else:
            raise ImportError(
                "No feature extractor available. Install sktime (recommended) or torch+momentfm"
            )
    
    elif backend == "minirocket":
        if not MINIROCKET_AVAILABLE:
            raise ImportError("MiniRocket not available. Install with: pip install sktime")
        return MiniRocketAdapter(**kwargs)
    
    elif backend == "moment":
        if not MOMENT_AVAILABLE:
            raise ImportError("MOMENT not available. Install with: pip install momentfm torch")
        return MomentAdapter(**kwargs)
    
    else:
        raise ValueError(f"Unknown backend: {backend}. Use 'auto', 'minirocket', or 'moment'.")


class ClassifierAdapter(IClassifier):
    """
    Adapter for XGBoost classifier.
    
    Wraps XGBClassifierWrapper to conform to IClassifier interface.
    
    Args:
        model_path: Optional path to pre-trained model file.
        
    Example:
        >>> adapter = ClassifierAdapter(model_path="models/xgb_demo.json")
        >>> predictions = adapter.predict(X)
        >>> probas = adapter.predict_proba(X)
    """
    
    def __init__(self, model_path: Optional[str] = None):
        self._classifier = XGBClassifierWrapper()
        if model_path:
            self._classifier.load_model(model_path)
    
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict categories."""
        return self._classifier.predict(X)
    
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict probabilities."""
        return self._classifier.predict_proba(X)
    
    def save_model(self, path: str) -> None:
        """Save model to file."""
        self._classifier.save_model(path)
    
    def load_model(self, path: str) -> None:
        """Load model from file."""
        self._classifier.load_model(path)
    
    def train(self, X: np.ndarray, y: np.ndarray):
        """Train the classifier (passthrough to underlying model)."""
        return self._classifier.train(X, y)
    
    @property
    def is_trained(self) -> bool:
        """Check if classifier is trained."""
        return self._classifier.is_trained


class FusionAdapter(IFeatureFusion):
    """
    Adapter for feature fusion.
    
    Wraps build_feature_vector to conform to IFeatureFusion interface.
    
    Example:
        >>> adapter = FusionAdapter()
        >>> feature_vec = adapter.fuse(
        ...     embedding=embedding,
        ...     baseline=baseline_result,
        ...     variability=var_result,
        ...     decelerations=decels,
        ...     tachysystole=tachy_result,
        ...     sinusoidal=sinus_result
        ... )
        >>> print(f"Feature vector shape: {feature_vec.vector.shape}")
    """
    
    def fuse(
        self,
        embedding: np.ndarray,
        baseline: IBaselineResult,
        variability: IVariabilityResult,
        decelerations: List[IDeceleration],
        tachysystole: ITachysystoleResult,
        sinusoidal: ISinusoidalResult,
        total_contractions: int = 0,
        v6: bool = True
    ) -> IFeatureVector:
        """Fuse features for V6 pipeline (MiniRocket+clinical, 10,004 dims) or legacy (1,035 dims)."""
        if v6:
            # V6 XGBoost was trained with MiniRocket (9,996) + 8 REAL clinical features
            # The 8 clinical features are:
            # 1. Baseline / 160
            # 2. Variability value / 25
            # 3. Late decel count / 10
            # 4. Variable decel count / 10
            # 5. Recurrent decels flag (0/1)
            # 6. Tachysystole flag (0/1)
            # 7. Sinusoidal flag (0/1)
            # 8. Variability category (0-3 normalized to 0-1)
            from src.models.fusion import V6FeatureVector
            from src.adapters.xgboost_only_classifier import MINIROCKET_FEATURES, TOTAL_FEATURES
            import numpy as np

            # 1. MiniRocket embedding (9,996)
            emb_arr = np.asarray(embedding, dtype=np.float32).ravel()
            if emb_arr.size != MINIROCKET_FEATURES:
                raise ValueError(f"MiniRocket embedding must be {MINIROCKET_FEATURES} dims, got {emb_arr.size}")

            # 2. Extract baseline value
            if hasattr(baseline, 'value'):
                baseline_value = baseline.value
            else:
                baseline_value = float(baseline)

            # 3. Extract variability
            if hasattr(variability, 'value'):
                var_value = variability.value
                var_category = getattr(variability, 'category', None)
            else:
                var_value = variability.get('value', 10.0) if isinstance(variability, dict) else 10.0
                var_category = variability.get('category', 'MODERATE') if isinstance(variability, dict) else 'MODERATE'

            # 4. Count decelerations by type
            late_count = 0
            variable_count = 0
            if decelerations:
                for d in decelerations:
                    dtype = getattr(d, 'decel_type', None)
                    if dtype is not None:
                        dtype_str = str(dtype.name if hasattr(dtype, 'name') else dtype).upper()
                        if 'LATE' in dtype_str:
                            late_count += 1
                        elif 'VARIABLE' in dtype_str:
                            variable_count += 1

            # 5. Recurrent decels (>50% of contractions or >3 decels)
            total_decels = len(decelerations) if decelerations else 0
            recurrent = total_decels >= 3

            # 6. Tachysystole flag
            tachy_detected = getattr(tachysystole, 'detected', False) if tachysystole else False

            # 7. Sinusoidal flag
            sinus_detected = getattr(sinusoidal, 'detected', False) if sinusoidal else False

            # 8. Variability category as number (0-3)
            category_map = {'ABSENT': 0, 'MINIMAL': 1, 'MODERATE': 2, 'MARKED': 3}
            if var_category is not None:
                cat_str = str(var_category.name if hasattr(var_category, 'name') else var_category).upper()
                var_cat_num = category_map.get(cat_str, 2)  # Default to MODERATE
            else:
                var_cat_num = 2  # MODERATE

            # Build the 8 clinical features (normalized)
            clinical_features = np.array([
                baseline_value / 160.0,           # 1. Baseline normalized
                var_value / 25.0,                 # 2. Variability normalized
                late_count / 10.0,                # 3. Late decel count normalized
                variable_count / 10.0,            # 4. Variable decel count normalized
                1.0 if recurrent else 0.0,        # 5. Recurrent decels flag
                1.0 if tachy_detected else 0.0,   # 6. Tachysystole flag
                1.0 if sinus_detected else 0.0,   # 7. Sinusoidal flag
                var_cat_num / 3.0,                # 8. Variability category normalized
            ], dtype=np.float32)

            # Concatenate: MiniRocket (9,996) + Clinical (8) = 10,004
            feature_vector = np.concatenate([emb_arr, clinical_features])

            if feature_vector.shape[0] != TOTAL_FEATURES:
                raise ValueError(f"V6 feature vector must be {TOTAL_FEATURES} dims, got {feature_vector.shape[0]}")

            return V6FeatureVector(
                vector=feature_vector,
                baseline=baseline_value,
                variability_value=var_value,
                variability_category=str(var_category.name if hasattr(var_category, 'name') else var_category) if var_category else 'MODERATE',
                late_decel_count=late_count,
                variable_decel_count=variable_count,
                recurrent_decels=recurrent,
                tachysystole=tachy_detected,
                sinusoidal=sinus_detected,
            )
        else:
            from src.models.fusion import build_feature_vector
            return build_feature_vector(
                embedding=embedding,
                baseline=baseline,
                variability=variability,
                decelerations=decelerations,
                tachysystole=tachysystole,
                sinusoidal=sinusoidal,
                start_idx=0,
                end_idx=0,
                start_time_sec=0,
                end_time_sec=0
            )
