"""
Adapters for model components.
These wrap existing model implementations to conform to Protocol interfaces.

Supports both MOMENT (legacy) and MiniRocket (recommended) encoders.
MiniRocket is 10-20x faster and uses 84 kernels vs 341M params.
"""

from typing import List, Optional, Union
from dataclasses import dataclass
import numpy as np
import logging

from src.interfaces.protocols import (
    IFeatureExtractor,
    IEmbeddingResult,
    IClassifier,
    IFeatureFusion,
    IFeatureVector,
    IBaselineResult,
    IVariabilityResult,
    IDeceleration,
    ITachysystoleResult,
    ISinusoidalResult,
)

# Try to import MiniRocket (preferred) or fallback to MOMENT
MINIROCKET_AVAILABLE = False
MOMENT_AVAILABLE = False

try:
    from src.models.minirocket_encoder import (
        MiniRocketEncoder, 
        MiniRocketConfig,
        generate_synthetic_training_data,
        SKTIME_AVAILABLE
    )
    MINIROCKET_AVAILABLE = SKTIME_AVAILABLE
except ImportError:
    pass

try:
    from src.models.moment_encoder import MomentFeatureExtractor, EmbeddingResult
    MOMENT_AVAILABLE = True
except ImportError:
    pass

from src.models.classifier import XGBClassifierWrapper
from src.models.fusion import build_feature_vector, FeatureVector

logger = logging.getLogger(__name__)


@dataclass
class AdapterEmbeddingResult:
    """
    Wrapper for embedding results from MomentFeatureExtractor.
    
    The MomentFeatureExtractor.extract() returns a raw numpy array,
    so this adapter wraps it to conform to IEmbeddingResult protocol.
    """
    _embedding: np.ndarray
    _is_mock: bool = False
    
    @property
    def embedding(self) -> np.ndarray:
        """1024-dimensional embedding vector."""
        return self._embedding
    
    @property
    def is_mock(self) -> bool:
        """True if this was generated by mock mode."""
        return self._is_mock


class MomentAdapter(IFeatureExtractor):
    """
    Adapter for MOMENT feature extractor (LEGACY - use MiniRocketAdapter instead).
    
    Wraps MomentFeatureExtractor to conform to IFeatureExtractor interface.
    
    NOTE: MOMENT requires PyTorch and momentfm packages. For faster inference,
    use MiniRocketAdapter instead (10-20x speedup).
    
    Args:
        use_mock: Use mock MOMENT (for testing without GPU).
        device: Device to use ('cpu', 'cuda', 'mps').
        
    Example:
        >>> adapter = MomentAdapter(use_mock=False, device='cuda')
        >>> result = adapter.extract(fhr_signal)
        >>> print(f"Embedding shape: {result.embedding.shape}")
    """
    
    def __init__(self, use_mock: bool = False, device: str = 'cpu'):
        if not MOMENT_AVAILABLE:
            raise ImportError(
                "MOMENT not available. Install with: pip install momentfm torch\n"
                "Or use MiniRocketAdapter instead (recommended)."
            )
        self._extractor = MomentFeatureExtractor(use_mock=use_mock, device=device)
        self._use_mock = use_mock or self._extractor.use_mock
    
    def extract(self, signal: np.ndarray) -> IEmbeddingResult:
        """Extract embeddings using MOMENT."""
        # MomentFeatureExtractor.extract() returns np.ndarray directly
        embedding_array = self._extractor.extract(signal)
        return AdapterEmbeddingResult(
            _embedding=embedding_array,
            _is_mock=self._use_mock
        )


class MiniRocketAdapter(IFeatureExtractor):
    """
    Adapter for MiniRocket feature extractor (RECOMMENDED).
    
    MiniRocket is 10-20x faster than MOMENT and uses only 84 kernels
    vs 341M parameters. Achieves comparable accuracy on CTG classification.
    
    Args:
        model_path: Path to pre-fitted MiniRocket model. If None or not found,
                   will attempt cold start with synthetic data.
        auto_fit: If True, automatically fit on synthetic data if no model found.
        
    Example:
        >>> adapter = MiniRocketAdapter()
        >>> result = adapter.extract(fhr_signal)
        >>> print(f"Feature shape: {result.embedding.shape}")
    """
    
    def __init__(
        self, 
        model_path: Optional[str] = "models/minirocket_encoder.joblib",
        auto_fit: bool = True
    ):
        if not MINIROCKET_AVAILABLE:
            raise ImportError(
                "MiniRocket not available. Install with: pip install sktime"
            )
        
        config = MiniRocketConfig(model_path=model_path)
        self._encoder = MiniRocketEncoder(config)
        
        # Cold start: fit on synthetic data if no pre-trained model
        if not self._encoder.is_fitted and auto_fit:
            logger.info("MiniRocket not fitted. Performing cold start with synthetic data...")
            X_synth, _ = generate_synthetic_training_data(n_samples=100)
            self._encoder.fit(X_synth)
            logger.info("Cold start complete. MiniRocket is ready.")
    
    def extract(self, signal: np.ndarray) -> IEmbeddingResult:
        """Extract features using MiniRocket."""
        result = self._encoder.extract_features(signal)
        return AdapterEmbeddingResult(
            _embedding=result.features,
            _is_mock=False
        )


def get_feature_extractor(
    backend: str = "auto",
    **kwargs
) -> IFeatureExtractor:
    """
    Factory function to get the best available feature extractor.
    
    Args:
        backend: One of 'auto', 'minirocket', 'moment'.
                'auto' prefers MiniRocket if available.
        **kwargs: Additional arguments passed to the adapter.
        
    Returns:
        IFeatureExtractor instance.
        
    Example:
        >>> extractor = get_feature_extractor()  # Auto-selects best
        >>> extractor = get_feature_extractor('minirocket')  # Force MiniRocket
    """
    if backend == "auto":
        if MINIROCKET_AVAILABLE:
            logger.info("Using MiniRocket feature extractor (recommended)")
            return MiniRocketAdapter(**kwargs)
        elif MOMENT_AVAILABLE:
            logger.warning("MiniRocket not available. Falling back to MOMENT (slower)")
            return MomentAdapter(**kwargs)
        else:
            raise ImportError(
                "No feature extractor available. Install sktime (recommended) or torch+momentfm"
            )
    
    elif backend == "minirocket":
        if not MINIROCKET_AVAILABLE:
            raise ImportError("MiniRocket not available. Install with: pip install sktime")
        return MiniRocketAdapter(**kwargs)
    
    elif backend == "moment":
        if not MOMENT_AVAILABLE:
            raise ImportError("MOMENT not available. Install with: pip install momentfm torch")
        return MomentAdapter(**kwargs)
    
    else:
        raise ValueError(f"Unknown backend: {backend}. Use 'auto', 'minirocket', or 'moment'.")


class ClassifierAdapter(IClassifier):
    """
    Adapter for XGBoost classifier.
    
    Wraps XGBClassifierWrapper to conform to IClassifier interface.
    
    Args:
        model_path: Optional path to pre-trained model file.
        
    Example:
        >>> adapter = ClassifierAdapter(model_path="models/xgb_demo.json")
        >>> predictions = adapter.predict(X)
        >>> probas = adapter.predict_proba(X)
    """
    
    def __init__(self, model_path: Optional[str] = None):
        self._classifier = XGBClassifierWrapper()
        if model_path:
            self._classifier.load_model(model_path)
    
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict categories."""
        return self._classifier.predict(X)
    
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict probabilities."""
        return self._classifier.predict_proba(X)
    
    def save_model(self, path: str) -> None:
        """Save model to file."""
        self._classifier.save_model(path)
    
    def load_model(self, path: str) -> None:
        """Load model from file."""
        self._classifier.load_model(path)
    
    def train(self, X: np.ndarray, y: np.ndarray):
        """Train the classifier (passthrough to underlying model)."""
        return self._classifier.train(X, y)
    
    @property
    def is_trained(self) -> bool:
        """Check if classifier is trained."""
        return self._classifier.is_trained


class FusionAdapter(IFeatureFusion):
    """
    Adapter for feature fusion.
    
    Wraps build_feature_vector to conform to IFeatureFusion interface.
    
    Example:
        >>> adapter = FusionAdapter()
        >>> feature_vec = adapter.fuse(
        ...     embedding=embedding,
        ...     baseline=baseline_result,
        ...     variability=var_result,
        ...     decelerations=decels,
        ...     tachysystole=tachy_result,
        ...     sinusoidal=sinus_result
        ... )
        >>> print(f"Feature vector shape: {feature_vec.vector.shape}")
    """
    
    def fuse(
        self,
        embedding: np.ndarray,
        baseline: IBaselineResult,
        variability: IVariabilityResult,
        decelerations: List[IDeceleration],
        tachysystole: ITachysystoleResult,
        sinusoidal: ISinusoidalResult
    ) -> IFeatureVector:
        """Fuse features using existing implementation."""
        return build_feature_vector(
            embedding=embedding,
            baseline=baseline,
            variability=variability,
            decelerations=decelerations,
            tachysystole=tachysystole,
            sinusoidal=sinusoidal,
            start_idx=0,
            end_idx=0,
            start_time_sec=0,
            end_time_sec=0
        )
